#Khinenw's PotionDispenser
name: EconomyPotionDispenser
author: Khinenw
version: "0.0.2"
description: "A potion dispenser for EconomyS"
main: Khinenw\PotionDispenser\Dispenser
api: 1.12.0
depend: [EconomyAPI]

permissions:
  potiondispenser.*:
    description: "The permission for using features of dispenser."
    default: op
    children:
      potiondispenser.use: 
        default: true
        description: "The permission for using dispenser."

      potiondispenser.create:
        default: op
        description: "The permission for creating dispensers."
      
      potiondispenser.destroy:
        default: op
        description: "The permission for destroying dispensers."
